voting/pages/urls.py
from django.urls import path
 
from . import views
 
urlpatterns = [
    path('', views.index, name ='index'),
]

voting/voting/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('pages.urls')),
    path('Votes/', include('votingapp.urls')),
    path('admin/', admin.site.urls),
]

voting/votingapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = 'votingapp'
urlpatterns = [
    path('', views.index, name ='index'),
    path('<int:question_id>/', views.detail,name ='detail'),
    path('<int:question_id>/results/', views.results,name ='results'),
    path('<int:question_id>/vote/', views.vote,name ='vote'),
]

voting/pages/models.py
from django.db import models

# Create your models here.

voting/votingapp/models.py
from django.db import models
 
# Create your models here.
 
class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('date published')
 
    def __str__(self):
        return self.question_text
 
 
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length = 200)
    votes = models.IntegerField(default = 0)
 
    def __str__(self):
        return self.choice_text

voting/pages/views.py
from django.shortcuts import render
 
# Create your views here.
 
def index(request):
    return render(request,'pages/index.html')

voting/votingapp/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect,Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
 
from .models import Question, Choice
 
 
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    #select * from question order by publisheddate limit by 5
    context = {'latest_question_list': latest_question_list}
    return render(request,'Votes/index.html', context)
 
# Show specific question and choices
 
 
def detail(request, question_id):
    try:
        question = Question.objects.get(pk = question_id)
        #select * from question  where question_id=3
        print(question)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request,'Votes/detail.html', {'question': question})
 
# Get question and display results
 
 
def results(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    #question=Question.object.get(pk = question_id)
    #choice = get_object_or_404(Choice, pk = question_id)
    #print(choice.votes)
    #Select * from question where q
    return render(request, 'Votes/results.html', {'question': question})
    #return render(request, 'Votes/results.html',responsedic)

 
# Vote for a question choice
 
 
def vote(request, question_id):
    # print(request.POST['choice'])
    question = get_object_or_404(Question, pk = question_id)
    #Question.object.get()
    try:
        selected_choice = question.choice_set.get(pk = request.POST['choice'])
        #select * from choice where choiceid=2
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'Votes/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('votingapp:results', args =(question.id, )))

voting/templates/Votes/detail.html
{% extends 'base.html' %}
{% block content %}
<a class ="btn btn-secondary btn-sm mb-3" href ="{% url 'votingapp:index' %}">Back To Polls</a>
<h1 class ="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class ="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>

{% endif %}

<form action ="{% url 'votingapp:vote' question.id %}" method ="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
	<div class ="form-check">
		<input type ="radio" name ="choice" class ="form-check-input" id ="choice{{ forloop.counter }}"
			value ="{{ choice.id }}" />
		<label for ="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
	</div>
	{% endfor %}
	<input type ="submit" value ="Vote" class ="btn btn-success btn-lg btn-block mt-4" />
</form>
{% endblock %}

voting/templates/Votes/index.html
{% extends 'base.html' %}
{% block content %}
<h1 class ="text-center mb-3"> Questions</h1>
{% if latest_question_list %}
{% for question in latest_question_list %}
<div class ="card-mb-3">
	<div class ="card-body">
		<div class="border border-2 rounded border-primary">
		<p class ="lead">{{ question.question_text }}</p>
		<p class ="lead">{{ question.pub_date }}</p>

		<a href ="{% url 'votingapp:detail' question.id %}" class ="btn btn-secondary btn-sm">Vote Now</a>
		<a href ="{% url 'votingapp:results' question.id %}" class ="btn btn-secondary btn-sm">Results</a>
	<br>
	<br>
	</div><br>
		</div>
	</div>
</div>
{% endfor %}
{% else %}

<p>No polls available</p>

{% endif %}
{% endblock %}

voting/templates/Votes/results.html
{% extends 'base.html' %}
{% block content %}
<h1 class ="mb-5 text-center">{{ question.question_text }}</h1>
<ul class ="list-group mb-5">
	{% for choice in question.choice_set.all %}
	<li class ="list-group-item">
		{{ choice.choice_text }} 		 <span>{{ choice.votes }}
			vote{{ choice.votes | pluralize }} </span>
	</li>
	<!-- {{votes}} -->
	{% endfor %}
</ul>

<a class ="btn btn-secondary" href ="{% url 'votingapp:index' %}">Back To Polls</a>
<a class ="btn btn-dark" href ="{% url 'votingapp:detail' question.id %}">Vote again?</a>
{% endblock %}

voting/templates/base.html
<html lang ="en">
<head>
   <title>VOTING  {% block title %}{% endblock %}</title>
</head>
<style>
    .myclass{
        background-color: ivory;
        color: blue;
    }
</style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
<body>
    <!--NavBar-->
    {% include 'partials/_navbar.html'%}
    <div class ="container ">
        <div class ="row">
            <div class =".col-md-6 m-auto ">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</body>
 
</html>

voting/templates/pages/index.html
{% extends 'base.html' %}
{% block content %}

<div class ="card text-center ">
	<div class ="card-body myclass">
		<h1>Welcome To Voting</h1>
		

		<a class ="btn btn-dark" href ="{% url 'votingapp:index' %}">
			View Polls</a>
	</div>
</div>
{% endblock %}

voting/templates/partials/_navbar.html

<nav class ="navbar navbar-dark bg-success mb-4">
    <div class ="container">
        <a class ="navbar-brand" href ="/">Voting App</a>
    </div>
</nav>